export const Catagories = ['Catagories A','Catagories B','Catagories C','Catagories D','Catagories E',]

export const MenuList = [
  'Catagories A',
  { id: 1, name: "Product A1" },
  { id: 2, name: "Product A2" },
  { id: 3, name: "Product A3" },
  { id: 4, name: "Product A4" },
  { id: 5, name: "Product A5" },
  { id: 6, name: "Product A6" },
  { id: 7, name: "Product A7" },
  { id: 8, name: "Product A8" },
  { id: 9, name: "Product A9" },
  'Catagories B',
  { id: 11, name: "Product B1" },
  { id: 12, name: "Product B2" },
  { id: 13, name: "Product B3" },
  { id: 14, name: "Product B4" },
  { id: 15, name: "Product B5" },
  { id: 16, name: "Product B6" },
  { id: 17, name: "Product B7" },
  { id: 18, name: "Product B8" },
  { id: 19, name: "Product B9" },
  'Catagories C',
  { id: 21, name: "Product C1" },
  { id: 22, name: "Product C2" },
  { id: 23, name: "Product C3" },
  { id: 24, name: "Product C4" },
  { id: 25, name: "Product C5" },
  { id: 26, name: "Product C6" },
  { id: 27, name: "Product C7" },
  { id: 28, name: "Product C8" },
  { id: 29, name: "Product C9" },
  'Catagories D',
  { id: 31, name: "Product D1" },
  { id: 32, name: "Product D2" },
  { id: 33, name: "Product D3" },
  { id: 34, name: "Product D4" },
  { id: 35, name: "Product D5" },
  { id: 36, name: "Product D6" },
  { id: 37, name: "Product D7" },
  { id: 38, name: "Product D8" },
  { id: 39, name: "Product D9" },
  'Catagories E',
  { id: 41, name: "Product E1" },
  { id: 42, name: "Product E2" },
  { id: 43, name: "Product E3" },
  { id: 44, name: "Product E4" },
  { id: 45, name: "Product E5" },
  { id: 46, name: "Product E6" },
  { id: 47, name: "Product E7" },
  { id: 48, name: "Product E8" },
  { id: 49, name: "Product E9" },
]